# Generated by Django 4.1.7 on 2023-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_test', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='acteurs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='realisateurs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
